# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pomodoro.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from .myWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(462, 326)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(462, 312))
        MainWindow.setMaximumSize(QtCore.QSize(11766, 11766))
        MainWindow.setBaseSize(QtCore.QSize(462, 312))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/window_image/tomato.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 421, 251))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.circleTimesLCD = CircleLCD(self.groupBox)
        self.circleTimesLCD.setGeometry(QtCore.QRect(10, 40, 71, 131))
        self.circleTimesLCD.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.circleTimesLCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.circleTimesLCD.setDigitCount(1)
        self.circleTimesLCD.setProperty("intValue", 0)
        self.circleTimesLCD.setObjectName("circleTimes")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 40, 321, 136))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.workLabel = MyLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workLabel.sizePolicy().hasHeightForWidth())
        self.workLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.workLabel.setFont(font)
        self.workLabel.setAutoFillBackground(False)
        self.workLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.workLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.workLabel.setLineWidth(1)
        self.workLabel.setTextFormat(QtCore.Qt.AutoText)
        self.workLabel.setScaledContents(False)
        self.workLabel.setWordWrap(False)
        self.workLabel.setObjectName("workLabel")
        self.gridLayout.addWidget(self.workLabel, 0, 0, 1, 1)
        self.long_restPB = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.long_restPB.setFont(font)
        self.long_restPB.setProperty("value", 100)
        self.long_restPB.setTextVisible(False)
        self.long_restPB.setObjectName("long_restPB")
        self.gridLayout.addWidget(self.long_restPB, 2, 1, 1, 1)
        self.restLabel = MyLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restLabel.sizePolicy().hasHeightForWidth())
        self.restLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.restLabel.setFont(font)
        self.restLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.restLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.restLabel.setObjectName("restLabel")
        self.gridLayout.addWidget(self.restLabel, 1, 0, 1, 1)
        self.restPB = QtWidgets.QProgressBar(self.layoutWidget)
        self.restPB.setProperty("value", 100)
        self.restPB.setTextVisible(False)
        self.restPB.setObjectName("restPB")
        self.gridLayout.addWidget(self.restPB, 1, 1, 1, 1)
        self.workPB = QtWidgets.QProgressBar(self.layoutWidget)
        self.workPB.setProperty("value", 100)
        self.workPB.setTextVisible(False)
        self.workPB.setInvertedAppearance(False)
        self.workPB.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.workPB.setObjectName("workPB")
        self.gridLayout.addWidget(self.workPB, 0, 1, 1, 1)
        self.longRestLabel = MyLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.longRestLabel.sizePolicy().hasHeightForWidth())
        self.longRestLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.longRestLabel.setFont(font)
        self.longRestLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.longRestLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.longRestLabel.setObjectName("longRestLabel")
        self.gridLayout.addWidget(self.longRestLabel, 2, 0, 1, 1)
        self.workCD = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workCD.sizePolicy().hasHeightForWidth())
        self.workCD.setSizePolicy(sizePolicy)
        self.workCD.setMinimumSize(QtCore.QSize(68, 36))
        self.workCD.setMaximumSize(QtCore.QSize(68, 36))
        self.workCD.setBaseSize(QtCore.QSize(68, 36))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.workCD.setFont(font)
        self.workCD.setFrameShape(QtWidgets.QFrame.Box)
        self.workCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.workCD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.workCD.setObjectName("workCD")
        self.gridLayout.addWidget(self.workCD, 0, 2, 1, 1)
        self.restCD = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restCD.sizePolicy().hasHeightForWidth())
        self.restCD.setSizePolicy(sizePolicy)
        self.restCD.setMinimumSize(QtCore.QSize(68, 36))
        self.restCD.setMaximumSize(QtCore.QSize(68, 36))
        self.restCD.setBaseSize(QtCore.QSize(68, 36))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.restCD.setFont(font)
        self.restCD.setFrameShape(QtWidgets.QFrame.Box)
        self.restCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.restCD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.restCD.setObjectName("restCD")
        self.gridLayout.addWidget(self.restCD, 1, 2, 1, 1)
        self.long_restCD = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.long_restCD.sizePolicy().hasHeightForWidth())
        self.long_restCD.setSizePolicy(sizePolicy)
        self.long_restCD.setMinimumSize(QtCore.QSize(68, 36))
        self.long_restCD.setMaximumSize(QtCore.QSize(68, 36))
        self.long_restCD.setBaseSize(QtCore.QSize(68, 36))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.long_restCD.setFont(font)
        self.long_restCD.setFrameShape(QtWidgets.QFrame.Box)
        self.long_restCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.long_restCD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.long_restCD.setObjectName("long_restCD")
        self.gridLayout.addWidget(self.long_restCD, 2, 2, 1, 1)
        self.restPB.raise_()
        self.longRestLabel.raise_()
        self.long_restPB.raise_()
        self.restLabel.raise_()
        self.workPB.raise_()
        self.workLabel.raise_()
        self.workCD.raise_()
        self.restCD.raise_()
        self.long_restCD.raise_()
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 180, 201, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlButton.sizePolicy().hasHeightForWidth())
        self.controlButton.setSizePolicy(sizePolicy)
        self.controlButton.setMinimumSize(QtCore.QSize(40, 40))
        self.controlButton.setMaximumSize(QtCore.QSize(40, 40))
        self.controlButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/control_panel/continue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.controlButton.setIcon(icon1)
        self.controlButton.setObjectName("controlButton")
        self.horizontalLayout.addWidget(self.controlButton)
        self.stopButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(40, 40))
        self.stopButton.setMaximumSize(QtCore.QSize(40, 40))
        self.stopButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/control_panel/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.optionButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionButton.sizePolicy().hasHeightForWidth())
        self.optionButton.setSizePolicy(sizePolicy)
        self.optionButton.setMinimumSize(QtCore.QSize(40, 40))
        self.optionButton.setMaximumSize(QtCore.QSize(40, 40))
        self.optionButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/control_panel/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.optionButton.setIcon(icon3)
        self.optionButton.setObjectName("optionButton")
        self.horizontalLayout.addWidget(self.optionButton)
        self.quitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quitButton.sizePolicy().hasHeightForWidth())
        self.quitButton.setSizePolicy(sizePolicy)
        self.quitButton.setMinimumSize(QtCore.QSize(40, 40))
        self.quitButton.setMaximumSize(QtCore.QSize(40, 40))
        self.quitButton.setBaseSize(QtCore.QSize(40, 40))
        self.quitButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/control_panel/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitButton.setIcon(icon4)
        self.quitButton.setObjectName("quitButton")
        self.horizontalLayout.addWidget(self.quitButton)
        self.counterButton = QtWidgets.QPushButton(self.groupBox)
        self.counterButton.setGeometry(QtCore.QRect(10, 190, 191, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.counterButton.setFont(font)
        self.counterButton.setObjectName("counterButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 462, 29))
        self.menubar.setObjectName("menubar")
        self.menuPreferences = QtWidgets.QMenu(self.menubar)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menuProfiles = QtWidgets.QMenu(self.menuPreferences)
        self.menuProfiles.setObjectName("menuProfiles")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu_Window = QtWidgets.QMenu(self.menubar)
        self.menu_Window.setObjectName("menu_Window")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setCheckable(False)
        self.actionOptions.setChecked(False)
        self.actionOptions.setObjectName("actionOptions")
        self.actionMinimum = QtWidgets.QAction(MainWindow)
        self.actionMinimum.setObjectName("actionMinimum")
        self.actionDonate = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/control_panel/money-bag-dollar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDonate.setIcon(icon5)
        self.actionDonate.setObjectName("actionDonate")
        self.actionRegister = QtWidgets.QAction(MainWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionCreate = QtWidgets.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionRemove = QtWidgets.QAction(MainWindow)
        self.actionRemove.setObjectName("actionRemove")
        self.menuProfiles.addAction(self.actionEdit)
        self.menuProfiles.addAction(self.actionCreate)
        self.menuProfiles.addAction(self.actionRemove)
        self.menuPreferences.addAction(self.actionOptions)
        self.menuPreferences.addAction(self.menuProfiles.menuAction())
        self.menuPreferences.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionDonate)
        self.menuHelp.addAction(self.actionRegister)
        self.menu_Window.addAction(self.actionMinimum)
        self.menu_Window.addAction(self.actionQuit)
        self.menubar.addAction(self.menuPreferences.menuAction())
        self.menubar.addAction(self.menu_Window.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.quitButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Eat Tomatoes!"))
        self.groupBox.setTitle(_translate("MainWindow", "Pomodoro Clock"))
        self.workLabel.setText(_translate("MainWindow", "Work"))
        self.restLabel.setText(_translate("MainWindow", "Rest"))
        self.longRestLabel.setText(_translate("MainWindow", "Long"))
        self.workCD.setText(_translate("MainWindow", "0"))
        self.restCD.setText(_translate("MainWindow", "0"))
        self.long_restCD.setText(_translate("MainWindow", "0"))
        self.counterButton.setText(_translate("MainWindow", "Counter"))
        self.menuPreferences.setTitle(_translate("MainWindow", "&Preferences"))
        self.menuProfiles.setTitle(_translate("MainWindow", "Profiles"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menu_Window.setTitle(_translate("MainWindow", "&Window"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionOptions.setText(_translate("MainWindow", "&Options"))
        self.actionOptions.setShortcut(_translate("MainWindow", "Ctrl+Shift+P"))
        self.actionMinimum.setText(_translate("MainWindow", "&Minimum"))
        self.actionDonate.setText(_translate("MainWindow", "Donate"))
        self.actionRegister.setText(_translate("MainWindow", "Register"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionHelp.setText(_translate("MainWindow", "Help for Eat Tomatoes!"))
        self.actionHelp.setShortcut(_translate("MainWindow", "?"))
        self.actionCreate.setText(_translate("MainWindow", "Create"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionRemove.setText(_translate("MainWindow", "Remove"))
from . import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
